language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - MONGO_VERSION=1.3.4
  - MONGO_VERSION=1.4.1

services: mongodb

before_script:
  - pecl -q install -f mongo-${MONGO_VERSION}
  - composer install --no-interaction --prefer-source
